# Generated by Django 3.2 on 2022-01-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pipeline_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('api_pipeline_id', models.CharField(max_length=100)),
                ('output_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('interval_start_date', models.DateField()),
                ('interval_end_date', models.DateField()),
                ('image_created_at', models.DateTimeField(blank=True)),
                ('image_updated_at', models.DateTimeField(blank=True)),
                ('image_previous_url', models.CharField(blank=True, max_length=400)),
                ('image_visual_url', models.CharField(blank=True, max_length=400)),
                ('image_analytics_url', models.CharField(blank=True, max_length=400)),
                ('image_metadata_url', models.CharField(blank=True, max_length=400)),
                ('image_size', models.CharField(blank=True, max_length=10)),
                ('image_valid_pixels_per', models.CharField(blank=True, max_length=10)),
                ('image_source', models.CharField(blank=True, max_length=60)),
                ('scene_height', models.CharField(blank=True, max_length=40)),
                ('scene_width', models.CharField(blank=True, max_length=40)),
                ('filled_area', models.CharField(blank=True, max_length=40)),
                ('aoi_area_per', models.CharField(blank=True, max_length=40)),
                ('cloud_cover_per', models.CharField(blank=True, max_length=40)),
                ('aoi_cloud_cover_per', models.CharField(blank=True, max_length=40)),
                ('visible_area', models.CharField(blank=True, max_length=40)),
                ('aoi_visible_area_per', models.CharField(blank=True, max_length=40)),
                ('pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceport.list')),
            ],
        ),
    ]
