# Generated by Django 3.2 on 2022-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0003_list_num_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
