# Generated by Django 3.2 on 2022-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0004_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='featured_image',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
    ]
