# Generated by Django 3.2 on 2022-01-17 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0005_list_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='aoi_area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='api_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='featured_image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='num_images',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='num_intervals',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='num_results',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='results_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
