# Generated by Django 3.2 on 2022-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0006_auto_20220117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='aoi_area_per',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='aoi_cloud_cover_per',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='aoi_visible_area_per',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cloud_cover_per',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='filled_area',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_analytics_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_metadata_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_previous_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_source',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_valid_pixels_per',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_visual_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='scene_height',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='scene_width',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='visible_area',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
