# Generated by Django 3.2 on 2022-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0007_auto_20220118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image_analytics_url',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_metadata_url',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_previous_url',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_visual_url',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
