# Generated by Django 3.2 on 2022-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0008_auto_20220120_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image_analytics_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_metadata_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_previous_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_visual_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
