# Generated by Django 3.2 on 2022-01-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0009_auto_20220120_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
