# Generated by Django 3.2 on 2022-01-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0010_list_time_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('complete', 'complete'), ('inactive', 'inactive')], max_length=30, null=True),
        ),
    ]
