# Generated by Django 3.2 on 2022-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0012_alter_list_output_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='output_image',
            field=models.CharField(choices=[('a8fc3dde-a3e8-11e7-9793-ae4260ee3b4b', 'True Colour'), ('1f0db8b2-b4d4-11e7-a775-a6fe70ce62b1', 'False Colour Urban'), ('154311a8-582a-11e7-b30d-7291b81e23e3', 'False Colour Infrared'), ('c31c1bea-a4be-11e7-8650-3ae5c7149ea7', 'All Optical Bands'), ('3cab2e68-b4d4-11e7-a775-a6fe70ce62b1', 'MSAVI2'), ('ga23d8a2-8f3d-481c-b7ef-9fa02839aab0', 'Near-infrared')], default='False Colour Urban', max_length=100),
        ),
    ]
