# Generated by Django 3.2 on 2022-01-27 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0015_auto_20220127_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cloud_cover',
            field=models.PositiveIntegerField(default=100, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
