# Generated by Django 3.2 on 2022-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0016_alter_list_cloud_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cloud_cover',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
