# Generated by Django 3.2 on 2022-01-27 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0017_alter_list_cloud_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='slug',
        ),
        migrations.AlterField(
            model_name='list',
            name='cloud_cover',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
